### ISSUE TITLE
G29 F 10.0

### ISSUE THREAD

**Issue by mrv96** [FrancYescO/Marlin1.1.9_LGT0.3.x_Alfawise_Ux0Pro#4]
According https://marlinfw.org/docs/gcode/G029-ubl.html, shouldn't you add G29 F 10.0 to LGT_SCR.cpp?

**Comment by FrancYescO** [comment]
> If no number is specified for the command, 10mm is assumed to be reasonable

is the default value.

**Comment by mrv96** [comment]
Thank you very much as always

________________________________
Da: Francesco M <notifications@github.com>
Inviato: Saturday, May 23, 2020 12:25:31 PM
A: FrancYescO/Marlin1.1.9_LGT0.3.x_Alfawise_Ux0Pro <Marlin1.1.9_LGT0.3.x_Alfawise_Ux0Pro@noreply.github.com>
Cc: mrv96 <marione96@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [FrancYescO/Marlin1.1.9_LGT0.3.x_Alfawise_Ux0Pro] G29 F 10.0 (#4)


If no number is specified for the command, 10mm is assumed to be reasonable

is the default value.
